services:
  # Frontend service with Bun
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      # Bind mount for source code hot reloading
      - .:/app
      # Named volume for node_modules performance
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=http://localhost:54321
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - supabase_network_cewgrolqmcuybnglzael
    command: bun run dev --host 0.0.0.0 --port ${FRONTEND_PORT:-3000} --force

volumes:
  # Named volume for node_modules performance optimization
  node_modules:
    driver: local

networks:
  supabase_network_cewgrolqmcuybnglzael:
    external: true
